"""cria chave_de_aplicacao

Revision ID: 40d7e4ba7213
Revises:
Create Date: 2026-08-11 22:56:38.285616

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40d7e4ba7213"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chave_de_aplicacao",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("aplicacao", sa.String(length=64), nullable=False),
        sa.Column("ambiente", sa.String(length=32), nullable=False),
        sa.Column(
            "natureza",
            sa.Enum(
                "do_projeto", "de_terceiro", name="naturezadachave", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("resumo_do_segredo", sa.String(length=64), nullable=False),
        sa.Column("emitida_por", sa.String(length=128), nullable=True),
        sa.Column(
            "emitida_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("prazo_de_apresentacao", sa.DateTime(timezone=True), nullable=True),
        sa.Column("url_apresentada", sa.String(length=512), nullable=True),
        sa.Column(
            "situacao",
            sa.Enum("vigente", "revogada", name="situacaodachave", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("revogada_por", sa.String(length=128), nullable=True),
        sa.Column("motivo_da_revogacao", sa.String(length=512), nullable=True),
        sa.Column("revogada_em", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_chave_vigente_por_aplicacao_e_ambiente",
        "chave_de_aplicacao",
        ["aplicacao", "ambiente"],
        unique=True,
        postgresql_where=sa.text("situacao = 'vigente'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_chave_vigente_por_aplicacao_e_ambiente",
        table_name="chave_de_aplicacao",
        postgresql_where=sa.text("situacao = 'vigente'"),
    )
    op.drop_table("chave_de_aplicacao")
    # ### end Alembic commands ###
